### ISSUE TITLE
Liquid Receive -> Fiat Switch doesn't work

### ISSUE THREAD

**Issue by kilrau** [AquaWallet/aqua-wallet#11]
Amount still L-BTC, supposedly L-BTC equivalent shows `2e-7` which is 0.0000002. Definitely a bug.
![image](https://github.com/AquaWallet/aqua-wallet/assets/19181985/ca73d5d2-2b9c-4785-9c20-3a229c6e502d)

**Comment by aquawallet-admin** [comment]
Thank you for your feedback. This will be fixed in our next release.

**Comment by aquawallet-admin** [comment]
Fixed in v0.1.51-bravo
