### ISSUE TITLE
Wallet don't load Boltz

### ISSUE THREAD

**Issue by jairunet** [AquaWallet/aqua-wallet#16]
When trying to create a lightning invoice the wallet continue showing the message "Loading Boltz" and doesn't move forward.

I tried restarting the app, restarting the Google Pixel 8 (with latest updates) but no luck.

![image](https://github.com/AquaWallet/aqua-wallet/assets/5609312/a028ae1d-f8f2-462b-b88f-3a2801ef5879)

Any suggestions or advice will be appreciated.

Sincerely,

**Comment by ascisco** [comment]
Same problem here, was able to reproduce on 2 different modern android phones.

**Comment by jairunet** [comment]
Actually, the issue is intermittent and goes away after a few minutes/hour.  It is working fine for my Google Pixel 8.

Hope this helps,

**Comment by jairunet** [comment]
What verion of Android are you running the wallet on? I am on a Google Pixel 8 Android version 14 with the latest updates.

**Comment by ascisco** [comment]
Pixel 6 and Pixel 7a, both phones are fully updated. Its weird because with my old Pixel 4a which has had aqua since Jan, has never had this problem.

**Comment by jairunet** [comment]
Interesting... I just tested and worked seemlessly.  I guess you can also do as I did in X/tweeter post the issue and tag the aqua wallet team: [@AquaBitcoin](https://twitter.com/AquaBitcoin)
