### ISSUE TITLE
Bug: 1st attempt to generate lightning invoice for receive always loads indefinitely, 2nd is super fast

### ISSUE THREAD

**Issue by tohrxyz** [AquaWallet/aqua-wallet#19]
My experience with aqua wallet has been great for the past month or so, but the thing that always frustrates me the most is, that whenever I want to create lightning invoice for receiving sats, the first one always keeps loading indefinitely.

I have to go back a screen, and then proceed to create it again and then it loads after a few seconds, nothing like the 1st one.

1. generate ln invoice -> loads indefinitely
2. cancel
3. create again -> loads in a few secs

This is really frustrating and I'm not sure what could be the problem, it has integration with boltz, maybe some sort of cold start for boltz api?

It would be really major thing to fix. Thanks for your ongoing work

**Comment by JoseHRosario** [comment]
I can confirm that it also happened to me.

**Comment by tohrxyz** [comment]
@JoseHRosario it is happening to me always. First never works, second immediately. 

I tried also ios and android version, the same bug happens.

**Comment by aquawallet-admin** [comment]
Fixed in v0.1.51-bravo. We have completely re-implemented the Receive Lightning flow natively.
