### ISSUE TITLE
Aqua doesn't set asset id for L-BTC BIP21 in QR

### ISSUE THREAD

**Issue by kilrau** [AquaWallet/aqua-wallet#22]
Two things:

- [ ] Aqua defaults to BIP21 in QRs for Receive -> USDT, but NOT in Receive -> L-BTC (here it's just the plain address). It should be BIP21 for both, even though no amount is set, Liquid is a multi-asset network and a plain address is not enough.
- [ ] For Liquid BIP21 asset type is mandatory and Aqua sets it in Receive -> USDT but NOT in Receive -> L-BTC *when setting amounts*, this is a clear violation of Liquid BIP21 where asset id is mandatory and causes other LIquid wallets like Green to error when scanning the QR.
![image](https://github.com/AquaWallet/aqua-wallet/assets/19181985/6e83cda0-59b6-45eb-aab3-f005c1216cc3)

**Comment by salvatoto** [comment]
Fixed in [v0.1.51](https://github.com/AquaWallet/aqua-wallet/tree/v0.1.51)](https://github.com/AquaWallet/aqua-wallet/releases/tag/v0.1.51)
