### ISSUE TITLE
Swap estimate is 2% fee

### ISSUE THREAD

**Issue by decentropy** [AquaWallet/aqua-wallet#32]
On-chain fees are currently only 9 sat/vB, but Aqua shows that I'll only get ~98% when I swap from Lbtc->Btc or vice-versa... even though sideswap.io shows the better estimate 99.9%

Maybe this estimate is wrong, but users won't want to even try... so the estimate should be fixed so we can swap in the app without going to sideswap.io

I am on 0.1.54(99) android

**Comment by salvatoto** [comment]
@decentropy This was a bug in receive amount estimate, although the actual amount received would have been correct. But both are fixed in 0.1.57.
