### ISSUE TITLE
Never ending "Restoring wallet"

### ISSUE THREAD

**Issue by levantah** [AquaWallet/aqua-wallet#36]
First I thought my problem was that I was restoring a BIP39 mnemonic never used before with Aqua. So I tried to restore mnemonic from another Aqua which is happily running on other phone (iPhone SE) on Android 11 (Lineage with all Google, running fine, Aqua installed from Play store) and still get the same never-ending "Restoring wallet". See attached video.

https://github.com/AquaWallet/aqua-wallet/assets/155245829/a59634bb-731e-4bbe-8c25-98e8890914cf

on iPhone: 0.1.57 (109)
on Android: 0.1.57 (never gets further than welcome screen, can't even create new wallet - all seems rather Android related because on iPhone I can delete the wallet and restore from BIP39 which was never-before used on Aqua)

**Comment by aquawallet-admin** [comment]
Might be caused by have an older Android OS. Will file an internal bug on this and look into it

**Comment by levantah** [comment]
Ah, sorry, this is releted just to my rooted developer Android. Everything works well on iPhone, even restoring a BIP39 never used before on Aqua Wallet.

**Comment by levantah** [comment]
Hmm, another thing: on a factory-reset Android where are can successfully
restore a previously-used 12-word seed, I can not restore a new valid BIP39
12-word seed.

Anyway, thanks for feedback!
