### ISSUE TITLE
Fees issue

### ISSUE THREAD

**Issue by FiliTol** [AquaWallet/aqua-wallet#4]
Fees fon LN payments and the swap (that are swaps in fact) are payed by the receiver, not the sender.

Example. 

- A wants to receive 1000 sats. Creates LN invoice for 1000 sats, then sends to B the invoice;
- B pays the invoice. The invoice is payed for 1000 sats;
- A receives (1000 - fees) sats. 

Fees approach should be consistent across all the Bitcoin apps and wallets I guess.

**Comment by aquawallet-admin** [comment]
Thank you for your suggestion. We will take this into consideration.
