### ISSUE TITLE
Reverse Swaps: Run Boltz Web View in background if there are swaps to claim

### ISSUE THREAD

**Issue by kilrau** [AquaWallet/aqua-wallet#5]
Web view should run whenever the app is active if there swaps to claim. Right now we need to instruct users to "create an invoice" to make the claim succeed :/

**Comment by kilrau** [comment]
Doesn't work for numerous users, e.g. https://twitter.com/sethforprivacy/status/1752806340446003615

**Comment by aquawallet-admin** [comment]
Thank you for your feedback. This is fixed on Android and waiting for iOS approval.

**Comment by aquawallet-admin** [comment]
Fixed in v0.1.51-bravo. Switched to native + boltz-rust claims in background.
