### ISSUE TITLE
Implement Aqua to Aqua Lightning sends via Liquid fallback

### ISSUE THREAD

**Issue by kilrau** [AquaWallet/aqua-wallet#8]

**Comment by kilrau** [comment]
We provided an easy fix for this, still not working in v0.1.25 Android:

![image](https://github.com/AquaWallet/aqua-wallet/assets/19181985/af4bebb8-1283-4140-8e61-8e59e2f6693d)

**Comment by aquawallet-admin** [comment]
Thank you for your suggestion. This will be added in our next release.

**Comment by aquawallet-admin** [comment]
Fixed in v0.1.51-bravo.
